"""Update

Revision ID: 505b97e17e77
Revises: 83e3109053f5
Create Date: 2023-01-04 23:22:17.600438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505b97e17e77'
down_revision = '83e3109053f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
