"""New

Revision ID: 7487a202c0cf
Revises: fdba6a0e73e0
Create Date: 2023-01-12 18:44:48.543569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7487a202c0cf'
down_revision = 'fdba6a0e73e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
