"""update

Revision ID: fdba6a0e73e0
Revises: 505b97e17e77
Create Date: 2023-01-12 15:46:05.666875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdba6a0e73e0'
down_revision = '505b97e17e77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
